State managment
dawidzon/React-Blog pull request #2
Opened 2023-02-23 03:24 UTC by dawidzon

I would like to ask you to check my homework.

2023-02-23 04:54 UTC, wozny1989 approved these changes
@dawidzon LGTM 👍

2023-02-23 04:54 UTC, wozny1989 commented on src/services/post.js
> +/* eslint-disable no-console */
✂️ 
```suggestion
```

2023-02-25 20:03 UTC, moraw9 requested changes
Good, only a few comments

2023-02-25 20:03 UTC, moraw9 commented on src/pages/PostDetails/PostDetails.jsx
> +  } = useQuery('post', () => postService.fetchPost(postId))
Query id has to be unique, so follow [this pattern](https://react-query-v3.tanstack.com/guides/query-keys#if-your-query-function-depends-on-a-variable-include-it-in-your-query-key).

2023-02-25 20:03 UTC, moraw9 commented on src/pages/PostDetails/PostDetails.jsx
> +    return <h1>{error.message}</h1>
Please use also  navigation to `NotFound` page, when not found error is returned

2023-02-26 21:38 UTC, moraw9 requested changes

2023-02-26 21:38 UTC, moraw9 commented on src/pages/PostDetails/PostDetails.jsx
> +  const handleBackHome = () => navigate('/not-found')
Function name suggests that you are navigated to hame, not to not found page, please change name

2023-02-26 21:38 UTC, moraw9 commented on src/pages/PostDetails/PostDetails.jsx
> +  const handleBackHome = () => navigate('/not-found')
And also not each error is related with not existing resource, so you need to handle navigation to not found page only when error is related with it

2023-02-26 21:38 UTC, moraw9 commented on src/pages/PostDetails/PostDetails.jsx
>            <h1>{post.title}</h1>
Don't you need to use `?.` after `post` ? What with initial rendering? I'm not sure if object exists.

2023-02-26 21:38 UTC, moraw9 commented on src/pages/PostsList/PostsList.jsx
> +  const handleBackHome = () => navigate('/not-found')
The same as above with `PostDetails`

2023-03-01 02:11 UTC, dawidzon commented
I'm not sure if these solutions are correct, but it is working

2023-03-02 07:11 UTC, moraw9 requested changes
Great, only one small change to do! 👍

2023-03-02 07:11 UTC, moraw9 commented on src/pages/PostDetails/PostDetails.jsx
> +  if (error?.message === 'Not found') {
Good! But also please display something if error is different than `Not found`

2023-03-02 07:11 UTC, moraw9 commented on src/pages/PostsList/PostsList.jsx
> +  if (error?.message === 'Not found') {
The same as above :D

2023-03-07 06:54 UTC, moraw9 requested changes
Only one small change to do :D

2023-03-07 06:54 UTC, moraw9 commented on src/pages/PostDetails/PostDetails.jsx
> +    } else if (error?.message !== 'Not found') {
Simply `else` is enough.

2023-03-07 06:54 UTC, moraw9 commented on src/pages/PostsList/PostsList.jsx
> +    } else if (error?.message !== 'Not found') {
Like above

2023-03-08 16:11 UTC, moraw9 approved these changes

2023-03-08 16:11 UTC, merged